services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: maria_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  # PHP Laravel Application
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
      - ./api/storage:/var/www/html/storage
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - mariadb
    networks:
      - app-network

  # React Application
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    container_name: spa
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./spa:/app
      - /app/node_modules
    ports:
      - "${SPA_PORT}:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge
